apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: auditclasses.audit.aunem.io
spec:
  group: audit.aunem.io
  names:
    kind: AuditClass
    plural: auditclasses
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            namespaces:
              items:
                type: string
              type: array
            nonResourceURLs:
              items:
                type: string
              type: array
            resources:
              items:
                properties:
                  group:
                    type: string
                  resourceNames:
                    items:
                      type: string
                    type: array
                  resources:
                    items:
                      type: string
                    type: array
                type: object
              type: array
            userGroups:
              items:
                type: string
              type: array
            users:
              items:
                type: string
              type: array
            verbs:
              items:
                type: string
              type: array
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
