apiVersion: auditregistration.k8s.io/v1alpha1
kind: AuditSink
metadata:
  name: testsink
spec:
  policy:
    level: Metadata
    stages:
    - ResponseComplete
  webhook:
    clientConfig:
      service:
        name: audit-proxy
        namespace: audit
      caBundle: ${CA_BUNDLE}