apiVersion: auditregistration.k8s.io/v1alpha1
kind: AuditSink
metadata:
  name: testsink
spec:
  policy:
    level: Metadata
    stages:
    - ResponseComplete
  webhook:
    clientConfig:
      url: "http://audit.audit-proxy.svc"