apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-proxy
  namespace: audit
  labels:
    app: audit-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit-proxy
  template:
    metadata:
      labels:
        app: audit-proxy
    spec:
      containers:
      - name: audit-proxy
        image: aunem/audit-proxy:latest
        ports:
        - containerPort: 443
        volumeMounts:
          - name: webhook-certs
            mountPath: /etc/webhook/certs
            readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: audit-proxy-webhook-certs