/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/pbarker/audit-lab/pkg/apis/audit/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAuditBackends implements AuditBackendInterface
type FakeAuditBackends struct {
	Fake *FakeAuditV1alpha1
	ns   string
}

var auditbackendsResource = schema.GroupVersionResource{Group: "audit.aunem.io", Version: "v1alpha1", Resource: "auditbackends"}

var auditbackendsKind = schema.GroupVersionKind{Group: "audit.aunem.io", Version: "v1alpha1", Kind: "AuditBackend"}

// Get takes name of the auditBackend, and returns the corresponding auditBackend object, and an error if there is any.
func (c *FakeAuditBackends) Get(name string, options v1.GetOptions) (result *v1alpha1.AuditBackend, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(auditbackendsResource, c.ns, name), &v1alpha1.AuditBackend{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AuditBackend), err
}

// List takes label and field selectors, and returns the list of AuditBackends that match those selectors.
func (c *FakeAuditBackends) List(opts v1.ListOptions) (result *v1alpha1.AuditBackendList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(auditbackendsResource, auditbackendsKind, c.ns, opts), &v1alpha1.AuditBackendList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AuditBackendList{ListMeta: obj.(*v1alpha1.AuditBackendList).ListMeta}
	for _, item := range obj.(*v1alpha1.AuditBackendList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested auditBackends.
func (c *FakeAuditBackends) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(auditbackendsResource, c.ns, opts))

}

// Create takes the representation of a auditBackend and creates it.  Returns the server's representation of the auditBackend, and an error, if there is any.
func (c *FakeAuditBackends) Create(auditBackend *v1alpha1.AuditBackend) (result *v1alpha1.AuditBackend, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(auditbackendsResource, c.ns, auditBackend), &v1alpha1.AuditBackend{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AuditBackend), err
}

// Update takes the representation of a auditBackend and updates it. Returns the server's representation of the auditBackend, and an error, if there is any.
func (c *FakeAuditBackends) Update(auditBackend *v1alpha1.AuditBackend) (result *v1alpha1.AuditBackend, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(auditbackendsResource, c.ns, auditBackend), &v1alpha1.AuditBackend{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AuditBackend), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAuditBackends) UpdateStatus(auditBackend *v1alpha1.AuditBackend) (*v1alpha1.AuditBackend, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(auditbackendsResource, "status", c.ns, auditBackend), &v1alpha1.AuditBackend{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AuditBackend), err
}

// Delete takes name of the auditBackend and deletes it. Returns an error if one occurs.
func (c *FakeAuditBackends) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(auditbackendsResource, c.ns, name), &v1alpha1.AuditBackend{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAuditBackends) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(auditbackendsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.AuditBackendList{})
	return err
}

// Patch applies the patch and returns the patched auditBackend.
func (c *FakeAuditBackends) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AuditBackend, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(auditbackendsResource, c.ns, name, pt, data, subresources...), &v1alpha1.AuditBackend{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AuditBackend), err
}
