/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	versioned "pkg/client/clientset/versioned"
	internalinterfaces "pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "pkg/client/listers/audit/v1alpha1"
	time "time"

	auditv1alpha1 "github.com/pbarker/audit-lab/pkg/apis/audit/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AuditBackendInformer provides access to a shared informer and lister for
// AuditBackends.
type AuditBackendInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.AuditBackendLister
}

type auditBackendInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAuditBackendInformer constructs a new informer for AuditBackend type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAuditBackendInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAuditBackendInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAuditBackendInformer constructs a new informer for AuditBackend type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAuditBackendInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AuditV1alpha1().AuditBackends(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AuditV1alpha1().AuditBackends(namespace).Watch(options)
			},
		},
		&auditv1alpha1.AuditBackend{},
		resyncPeriod,
		indexers,
	)
}

func (f *auditBackendInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAuditBackendInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *auditBackendInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&auditv1alpha1.AuditBackend{}, f.defaultInformer)
}

func (f *auditBackendInformer) Lister() v1alpha1.AuditBackendLister {
	return v1alpha1.NewAuditBackendLister(f.Informer().GetIndexer())
}
