apiVersion: audit.aunem.io/v1alpha1
kind: AuditClass
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: sample
spec:
  resources:
  - group: "" # core API group
    resources: ["secrets", "configmaps", "pods", "services", "deployments"]
